class QuranModel {
  int id;
  String titleInArabic;
  String titleInEnglish;
  int vercesCount;

  QuranModel({
    required this.id,
    required this.titleInArabic,
    required this.titleInEnglish,
    required this.vercesCount,
  });

  static List<QuranModel> quran = [
    QuranModel(
      id: 1,
      titleInArabic: 'الفاتحة',
      titleInEnglish: 'Al-Fatihah',
      vercesCount: 7,
    ),
    QuranModel(
      id: 2,
      titleInArabic: 'البقرة',
      titleInEnglish: 'Al-Baqarah',
      vercesCount: 286,
    ),
    QuranModel(
      id: 3,
      titleInArabic: 'آل عمران',
      titleInEnglish: 'Aal-E-Imran',
      vercesCount: 200,
    ),
    QuranModel(
      id: 4,
      titleInArabic: 'النساء',
      titleInEnglish: 'An-Nisa',
      vercesCount: 176,
    ),
    QuranModel(
      id: 5,
      titleInArabic: 'المائدة',
      titleInEnglish: 'Al-Maidah',
      vercesCount: 120,
    ),
    QuranModel(
      id: 6,
      titleInArabic: 'الأنعام',
      titleInEnglish: 'Al-Anam',
      vercesCount: 165,
    ),
    QuranModel(
      id: 7,
      titleInArabic: 'الأعراف',
      titleInEnglish: 'Al-Araf',
      vercesCount: 206,
    ),
    QuranModel(
      id: 8,
      titleInArabic: 'الأنفال',
      titleInEnglish: 'Al-Anfal',
      vercesCount: 75,
    ),
    QuranModel(
      id: 9,
      titleInArabic: 'التوبة',
      titleInEnglish: 'At-Tawbah',
      vercesCount: 129,
    ),
    QuranModel(
      id: 10,
      titleInArabic: 'يونس',
      titleInEnglish: 'Yunus',
      vercesCount: 109,
    ),
    QuranModel(
      id: 11,
      titleInArabic: 'هود',
      titleInEnglish: 'Hud',
      vercesCount: 123,
    ),
    QuranModel(
      id: 12,
      titleInArabic: 'يوسف',
      titleInEnglish: 'Yusuf',
      vercesCount: 111,
    ),
    QuranModel(
      id: 13,
      titleInArabic: 'الرعد',
      titleInEnglish: 'Ar-Rad',
      vercesCount: 43,
    ),
    QuranModel(
      id: 14,
      titleInArabic: 'إبراهيم',
      titleInEnglish: 'Ibrahim',
      vercesCount: 52,
    ),
    QuranModel(
      id: 15,
      titleInArabic: 'الحجر',
      titleInEnglish: 'Al-Hijr',
      vercesCount: 99,
    ),
    QuranModel(
      id: 16,
      titleInArabic: 'النحل',
      titleInEnglish: 'An-Nahl',
      vercesCount: 128,
    ),
    QuranModel(
      id: 17,
      titleInArabic: 'الإسراء',
      titleInEnglish: 'Al-Isra',
      vercesCount: 111,
    ),
    QuranModel(
      id: 18,
      titleInArabic: 'الكهف',
      titleInEnglish: 'Al-Kahf',
      vercesCount: 110,
    ),
    QuranModel(
      id: 19,
      titleInArabic: 'مريم',
      titleInEnglish: 'Maryam',
      vercesCount: 98,
    ),
    QuranModel(
      id: 20,
      titleInArabic: 'طه',
      titleInEnglish: 'Taha',
      vercesCount: 135,
    ),
    QuranModel(
      id: 21,
      titleInArabic: 'الأنبياء',
      titleInEnglish: 'Al-Anbiya',
      vercesCount: 112,
    ),
    QuranModel(
      id: 22,
      titleInArabic: 'الحج',
      titleInEnglish: 'Al-Hajj',
      vercesCount: 78,
    ),
    QuranModel(
      id: 23,
      titleInArabic: 'المؤمنون',
      titleInEnglish: 'Al-Mumenoon',
      vercesCount: 118,
    ),
    QuranModel(
      id: 24,
      titleInArabic: 'النور',
      titleInEnglish: 'An-Noor',
      vercesCount: 64,
    ),
    QuranModel(
      id: 25,
      titleInArabic: 'الفرقان',
      titleInEnglish: 'Al-Furqan',
      vercesCount: 77,
    ),
    QuranModel(
      id: 26,
      titleInArabic: 'الشعراء',
      titleInEnglish: 'Ash-Shuara',
      vercesCount: 227,
    ),
    QuranModel(
      id: 27,
      titleInArabic: 'النمل',
      titleInEnglish: 'An-Naml',
      vercesCount: 93,
    ),
    QuranModel(
      id: 28,
      titleInArabic: 'القصص',
      titleInEnglish: 'Al-Qasas',
      vercesCount: 88,
    ),
    QuranModel(
      id: 29,
      titleInArabic: 'العنكبوت',
      titleInEnglish: 'Al-Ankaboot',
      vercesCount: 69,
    ),
    QuranModel(
      id: 30,
      titleInArabic: 'الروم',
      titleInEnglish: 'Ar-Room',
      vercesCount: 60,
    ),
    QuranModel(
      id: 31,
      titleInArabic: 'لقمان',
      titleInEnglish: 'Luqman',
      vercesCount: 34,
    ),
    QuranModel(
      id: 32,
      titleInArabic: 'السجدة',
      titleInEnglish: 'As-Sajda',
      vercesCount: 30,
    ),
    QuranModel(
      id: 33,
      titleInArabic: 'الأحزاب',
      titleInEnglish: 'Al-Ahzab',
      vercesCount: 73,
    ),
    QuranModel(
      id: 34,
      titleInArabic: 'سبأ',
      titleInEnglish: 'Saba',
      vercesCount: 54,
    ),
    QuranModel(
      id: 35,
      titleInArabic: 'فاطر',
      titleInEnglish: 'Faatir',
      vercesCount: 45,
    ),
    QuranModel(
      id: 36,
      titleInArabic: 'يس',
      titleInEnglish: 'Yaseen',
      vercesCount: 83,
    ),
    QuranModel(
      id: 37,
      titleInArabic: 'الصافات',
      titleInEnglish: 'As-Saaffaat',
      vercesCount: 182,
    ),
    QuranModel(
      id: 38,
      titleInArabic: 'ص',
      titleInEnglish: 'Saad',
      vercesCount: 88,
    ),
    QuranModel(
      id: 39,
      titleInArabic: 'الزمر',
      titleInEnglish: 'Az-Zumar',
      vercesCount: 75,
    ),
    QuranModel(
      id: 40,
      titleInArabic: 'غافر',
      titleInEnglish: 'Ghafir',
      vercesCount: 85,
    ),
    QuranModel(
      id: 41,
      titleInArabic: 'فصلت',
      titleInEnglish: 'Fussilat',
      vercesCount: 54,
    ),
    QuranModel(
      id: 42,
      titleInArabic: 'الشورى',
      titleInEnglish: 'Ash-Shura',
      vercesCount: 53,
    ),
    QuranModel(
      id: 43,
      titleInArabic: 'الزخرف',
      titleInEnglish: 'Az-Zukhruf',
      vercesCount: 89,
    ),
    QuranModel(
      id: 44,
      titleInArabic: 'الدخان',
      titleInEnglish: 'Ad-Dukhan',
      vercesCount: 59,
    ),
    QuranModel(
      id: 45,
      titleInArabic: 'الجاثية',
      titleInEnglish: 'Al-Jathiya',
      vercesCount: 37,
    ),
    QuranModel(
      id: 46,
      titleInArabic: 'الأحقاف',
      titleInEnglish: 'Al-Ahqaf',
      vercesCount: 35,
    ),
    QuranModel(
      id: 47,
      titleInArabic: 'محمد',
      titleInEnglish: 'Muhammad',
      vercesCount: 38,
    ),
    QuranModel(
      id: 48,
      titleInArabic: 'الفتح',
      titleInEnglish: 'Al-Fath',
      vercesCount: 29,
    ),
    QuranModel(
      id: 49,
      titleInArabic: 'الحجرات',
      titleInEnglish: 'Al-Hujurat',
      vercesCount: 18,
    ),
    QuranModel(
      id: 50,
      titleInArabic: 'ق',
      titleInEnglish: 'Qaaf',
      vercesCount: 45,
    ),
    QuranModel(
      id: 51,
      titleInArabic: 'الذاريات',
      titleInEnglish: 'Adh-Dhariyat',
      vercesCount: 60,
    ),
    QuranModel(
      id: 52,
      titleInArabic: 'الطور',
      titleInEnglish: 'At-Tur',
      vercesCount: 49,
    ),
    QuranModel(
      id: 53,
      titleInArabic: 'النجم',
      titleInEnglish: 'An-Najm',
      vercesCount: 62,
    ),
    QuranModel(
      id: 54,
      titleInArabic: 'القمر',
      titleInEnglish: 'Al-Qamar',
      vercesCount: 55,
    ),
    QuranModel(
      id: 55,
      titleInArabic: 'الرحمن',
      titleInEnglish: 'Ar-Rahman',
      vercesCount: 78,
    ),
    QuranModel(
      id: 56,
      titleInArabic: 'الواقعة',
      titleInEnglish: 'Al-Waqia',
      vercesCount: 96,
    ),
    QuranModel(
      id: 57,
      titleInArabic: 'الحديد',
      titleInEnglish: 'Al-Hadid',
      vercesCount: 29,
    ),
    QuranModel(
      id: 58,
      titleInArabic: 'المجادلة',
      titleInEnglish: 'Al-Mujadila',
      vercesCount: 22,
    ),
    QuranModel(
      id: 59,
      titleInArabic: 'الحشر',
      titleInEnglish: 'Al-Hashr',
      vercesCount: 24,
    ),
    QuranModel(
      id: 60,
      titleInArabic: 'الممتحنة',
      titleInEnglish: 'Al-Mumtahina',
      vercesCount: 13,
    ),
    QuranModel(
      id: 61,
      titleInArabic: 'الصف',
      titleInEnglish: 'As-Saff',
      vercesCount: 14,
    ),
    QuranModel(
      id: 62,
      titleInArabic: 'الجمعة',
      titleInEnglish: 'Al-Jumua',
      vercesCount: 11,
    ),
    QuranModel(
      id: 63,
      titleInArabic: 'المنافقون',
      titleInEnglish: 'Al-Munafiqoon',
      vercesCount: 11,
    ),
    QuranModel(
      id: 64,
      titleInArabic: 'التغابن',
      titleInEnglish: 'At-Taghabun',
      vercesCount: 18,
    ),
    QuranModel(
      id: 65,
      titleInArabic: 'الطلاق',
      titleInEnglish: 'At-Talaq',
      vercesCount: 12,
    ),
    QuranModel(
      id: 66,
      titleInArabic: 'التحريم',
      titleInEnglish: 'At-Tahrim',
      vercesCount: 12,
    ),
    QuranModel(
      id: 67,
      titleInArabic: 'الملك',
      titleInEnglish: 'Al-Mulk',
      vercesCount: 30,
    ),
    QuranModel(
      id: 68,
      titleInArabic: 'القلم',
      titleInEnglish: 'Al-Qalam',
      vercesCount: 52,
    ),
    QuranModel(
      id: 69,
      titleInArabic: 'الحاقة',
      titleInEnglish: 'Al-Haaqqa',
      vercesCount: 52,
    ),
    QuranModel(
      id: 70,
      titleInArabic: 'المعارج',
      titleInEnglish: 'Al-Maarij',
      vercesCount: 44,
    ),
    QuranModel(
      id: 71,
      titleInArabic: 'نوح',
      titleInEnglish: 'Nuh',
      vercesCount: 28,
    ),
    QuranModel(
      id: 72,
      titleInArabic: 'الجن',
      titleInEnglish: 'Al-Jinn',
      vercesCount: 28,
    ),
    QuranModel(
      id: 73,
      titleInArabic: 'المزمل',
      titleInEnglish: 'Al-Muzzammil',
      vercesCount: 20,
    ),
    QuranModel(
      id: 74,
      titleInArabic: 'المدثر',
      titleInEnglish: 'Al-Muddathir',
      vercesCount: 56,
    ),
    QuranModel(
      id: 75,
      titleInArabic: 'القيامة',
      titleInEnglish: 'Al-Qiyama',
      vercesCount: 40,
    ),
    QuranModel(
      id: 76,
      titleInArabic: 'الإنسان',
      titleInEnglish: 'Al-Insan',
      vercesCount: 31,
    ),
    QuranModel(
      id: 77,
      titleInArabic: 'المرسلات',
      titleInEnglish: 'Al-Mursalat',
      vercesCount: 50,
    ),
    QuranModel(
      id: 78,
      titleInArabic: 'النبأ',
      titleInEnglish: 'An-Naba',
      vercesCount: 40,
    ),
    QuranModel(
      id: 79,
      titleInArabic: 'النازعات',
      titleInEnglish: 'An-Naziat',
      vercesCount: 46,
    ),
    QuranModel(
      id: 80,
      titleInArabic: 'عبس',
      titleInEnglish: 'Abasa',
      vercesCount: 42,
    ),
    QuranModel(
      id: 81,
      titleInArabic: 'التكوير',
      titleInEnglish: 'At-Takwir',
      vercesCount: 29,
    ),
    QuranModel(
      id: 82,
      titleInArabic: 'الإنفطار',
      titleInEnglish: 'Al-Infitar',
      vercesCount: 19,
    ),
    QuranModel(
      id: 83,
      titleInArabic: 'المطففين',
      titleInEnglish: 'Al-Mutaffifin',
      vercesCount: 36,
    ),
    QuranModel(
      id: 84,
      titleInArabic: 'الإنشقاق',
      titleInEnglish: 'Al-Inshiqaq',
      vercesCount: 25,
    ),
    QuranModel(
      id: 85,
      titleInArabic: 'البروج',
      titleInEnglish: 'Al-Burooj',
      vercesCount: 22,
    ),
    QuranModel(
      id: 86,
      titleInArabic: 'الطارق',
      titleInEnglish: 'At-Tariq',
      vercesCount: 17,
    ),
    QuranModel(
      id: 87,
      titleInArabic: 'الأعلى',
      titleInEnglish: 'Al-Ala',
      vercesCount: 19,
    ),
    QuranModel(
      id: 88,
      titleInArabic: 'الغاشية',
      titleInEnglish: 'Al-Ghashiya',
      vercesCount: 26,
    ),
    QuranModel(
      id: 89,
      titleInArabic: 'الفجر',
      titleInEnglish: 'Al-Fajr',
      vercesCount: 30,
    ),
    QuranModel(
      id: 90,
      titleInArabic: 'البلد',
      titleInEnglish: 'Al-Balad',
      vercesCount: 20,
    ),
    QuranModel(
      id: 91,
      titleInArabic: 'الشمس',
      titleInEnglish: 'Ash-Shams',
      vercesCount: 15,
    ),
    QuranModel(
      id: 92,
      titleInArabic: 'الليل',
      titleInEnglish: 'Al-Lail',
      vercesCount: 21,
    ),
    QuranModel(
      id: 93,
      titleInArabic: 'الضحى',
      titleInEnglish: 'Ad-Duha',
      vercesCount: 11,
    ),
    QuranModel(
      id: 94,
      titleInArabic: 'الشرح',
      titleInEnglish: 'Ash-Sharh',
      vercesCount: 8,
    ),
    QuranModel(
      id: 95,
      titleInArabic: 'التين',
      titleInEnglish: 'At-Tin',
      vercesCount: 8,
    ),
    QuranModel(
      id: 96,
      titleInArabic: 'العلق',
      titleInEnglish: 'Al-Alaq',
      vercesCount: 19,
    ),
    QuranModel(
      id: 97,
      titleInArabic: 'القدر',
      titleInEnglish: 'Al-Qadr',
      vercesCount: 5,
    ),
    QuranModel(
      id: 98,
      titleInArabic: 'البينة',
      titleInEnglish: 'Al-Bayyina',
      vercesCount: 8,
    ),
    QuranModel(
      id: 99,
      titleInArabic: 'الزلزلة',
      titleInEnglish: 'Az-Zalzalah',
      vercesCount: 8,
    ),
    QuranModel(
      id: 100,
      titleInArabic: 'العاديات',
      titleInEnglish: 'Al-Adiyat',
      vercesCount: 11,
    ),
    QuranModel(
      id: 101,
      titleInArabic: 'القارعة',
      titleInEnglish: 'Al-Qariah',
      vercesCount: 11,
    ),
    QuranModel(
      id: 102,
      titleInArabic: 'التكاثر',
      titleInEnglish: 'At-Takathur',
      vercesCount: 8,
    ),
    QuranModel(
      id: 103,
      titleInArabic: 'العصر',
      titleInEnglish: 'Al-Asr',
      vercesCount: 3,
    ),
    QuranModel(
      id: 104,
      titleInArabic: 'الهمزة',
      titleInEnglish: 'Al-Humazah',
      vercesCount: 9,
    ),
    QuranModel(
      id: 105,
      titleInArabic: 'الفيل',
      titleInEnglish: 'Al-Fil',
      vercesCount: 5,
    ),
    QuranModel(
      id: 106,
      titleInArabic: 'قريش',
      titleInEnglish: 'Quraish',
      vercesCount: 4,
    ),
    QuranModel(
      id: 107,
      titleInArabic: 'الماعون',
      titleInEnglish: 'Al-Maun',
      vercesCount: 7,
    ),
    QuranModel(
      id: 108,
      titleInArabic: 'الكوثر',
      titleInEnglish: 'Al-Kawthar',
      vercesCount: 3,
    ),
    QuranModel(
      id: 109,
      titleInArabic: 'الكافرون',
      titleInEnglish: 'Al-Kafiroon',
      vercesCount: 6,
    ),
    QuranModel(
      id: 110,
      titleInArabic: 'النصر',
      titleInEnglish: 'An-Nasr',
      vercesCount: 3,
    ),
    QuranModel(
      id: 111,
      titleInArabic: 'المسد',
      titleInEnglish: 'Al-Masad',
      vercesCount: 5,
    ),
    QuranModel(
      id: 112,
      titleInArabic: 'الإخلاص',
      titleInEnglish: 'Al-Ikhlas',
      vercesCount: 4,
    ),
    QuranModel(
      id: 113,
      titleInArabic: 'الفلق',
      titleInEnglish: 'Al-Falaq',
      vercesCount: 5,
    ),
    QuranModel(
      id: 114,
      titleInArabic: 'الناس',
      titleInEnglish: 'An-Nas',
      vercesCount: 6,
    ),
  ];
}
